name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
         to: 181137011 
         token: 7549151423:AAHDeCkAOc9idbYAIM1ehO3uIqJ7kXMmEP0
         message: Миронов Ермолаев Карболин
