name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: send telegram message on push
       uses: appleboy/telegram-action@master
       with:
         to: 1679015248
         token: 7223325949:AAHm5sWZ-GOWYXTopQCnDQkIc3cpCoFPCo4
         message: Миронов Ермолаев Карболин
